/* generated by template templates.de.monticore.lang.tagschema.TagSchema*/


package nfp.TransmissionCostsTagSchema;

import de.monticore.lang.tagging._symboltable.TaggingResolver;
import de.monticore.symboltable.resolving.CommonResolvingFilter;

/**
 * generated by TagSchema.ftl
 */
public class TransmissionCostsTagSchema {

  protected static TransmissionCostsTagSchema instance = null;

  protected TransmissionCostsTagSchema() {}

  protected static TransmissionCostsTagSchema getInstance() {
    if (instance == null) {
      instance = new TransmissionCostsTagSchema();
    }
    return instance;
  }

  protected void doRegisterTagTypes(TaggingResolver tagging) {
    tagging.addTagSymbolCreator(new TransCostCmpInstSymbolCreator());
    tagging.addTagSymbolResolvingFilter(CommonResolvingFilter.create(TransCostCmpInstSymbol.KIND));
    tagging.addTagSymbolCreator(new TransCostCmpSymbolCreator());
    tagging.addTagSymbolResolvingFilter(CommonResolvingFilter.create(TransCostCmpSymbol.KIND));
    tagging.addTagSymbolCreator(new TransCostConnSymbolCreator());
    tagging.addTagSymbolResolvingFilter(CommonResolvingFilter.create(TransCostConnSymbol.KIND));
    tagging.addTagSymbolCreator(new TransCostPortSymbolCreator());
    tagging.addTagSymbolResolvingFilter(CommonResolvingFilter.create(TransCostPortSymbol.KIND));
  }

  public static void registerTagTypes(TaggingResolver tagging) {
    getInstance().doRegisterTagTypes(tagging);
  }

}