/* generated by template templates.de.monticore.lang.tagschema.ValuedTagType*/


package nfp.TransmissionCostsTagSchema;

import de.monticore.lang.tagging._symboltable.TagKind;
import de.monticore.lang.tagging._symboltable.TagSymbol;

import org.jscience.physics.amount.Amount;
import javax.measure.quantity.Power;
import javax.measure.unit.Unit;

/**
 * Created by ValuedTagType.ftl
 */
public class TransCostPortSymbol extends TagSymbol {
  public static final TransCostPortKind KIND = TransCostPortKind.INSTANCE;

  public TransCostPortSymbol(Amount<Power> value) {
    this(KIND, value);
  }

  public TransCostPortSymbol(Number number, Unit<Power> unit) {
    this(KIND, number, unit);
  }

  protected TransCostPortSymbol(TransCostPortKind kind, Amount<Power> value) {
    super(kind, value);
  }

  protected TransCostPortSymbol(TransCostPortKind kind, Number number, Unit<Power> unit) {
    this(kind, number.toString().contains(".") ?
      Amount.valueOf(number.doubleValue(), unit) :
      Amount.valueOf(number.intValue(),
          unit));
  }

  public Amount<Power> getValue() {
     return getValue(0);
  }

  public Number getNumber() {
    return getValue().getExactValue();
  }

  public Unit<Power> getUnit() {
    return getValue().getUnit();
  }

  @Override
  public String toString() {
    return String.format("TransCostPort = %s %s",
      getNumber(), getUnit());
  }

  public static class TransCostPortKind extends TagKind {
    public static final TransCostPortKind INSTANCE = new TransCostPortKind();

    protected TransCostPortKind() {
    }
  }
}