version: "2"

checks:
  argument-count:
    config:
      threshold: 7
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
    config:
      threshold: 100 # language-specific defaults. an override will affect all languages.
  identical-code:
    enabled: false
    config:
      threshold: 100 # language-specific defaults. an override will affect all languages.


plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "8"
      minimum_severity: minor
      tests_patterns:
        - "**/test/"
        - "**/acceptance-test/"
        - "**/integration-test/"


exclude_patterns:
  - "**/target/"
  - "**/defaultTypes/"
  - "libraries/"
  - "**/generated-test-sources/"
  - "docs/"
  - "services/recorder/lib/**"
  - "services/log-tracing/lib/**"
  - "services/log-tracing/frontend/public/**"
  - "services/recorder/lib/**"
  - "generators/montithings2cpp/src/main/resources/test/gtests/lib/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/cereal/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/cpp-httplib/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/easyloggingpp/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/json/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/nngpp/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/rigtorp/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/sole/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/tclap/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/tl/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/record-and-replay/message-types/**"
  - "generators/montithings2cpp/src/main/resources/rte/montithings-RTE/logtracing/interface/dds/message-types/**"
  - "**/src/test/**"
  - "**/src/integration-test/**"
  - "**/src/acceptance-test/**"
  - "docs/**"

