/* generated by template templates.de.monticore.lang.tagschema.ComplexTagType*/


package nfp.RosToEmamTagSchema;

import de.monticore.lang.tagging._symboltable.TagKind;
import de.monticore.lang.tagging._symboltable.TagSymbol;

import org.jscience.physics.amount.Amount;
import javax.measure.quantity.*;

/**
 * Created by ValuedTagType.ftl
 */
public class RosConnectionSymbol extends TagSymbol {
  public static final RosConnectionKind KIND = RosConnectionKind.INSTANCE;

  public RosConnectionSymbol(
    Amount<?> topicName,
    Amount<?> msgField,
    Amount<?> topicType
  ) {
    super(KIND,
    (Amount<String>)topicName,
    (Amount<String>)msgField,
    (Amount<String>)topicType
    );
  }

  public String getTopicName() {
    return getValue(0);
  }

  public String getMsgField() {
    return getValue(1);
  }

  public String getTopicType() {
    return getValue(2);
  }


  @Override
  public String toString() {
    return String.format("RosConnection = " +
    "%s"+
    "%s"+
    "%s"
    ,
    getTopicName(),
    getMsgField(),
    getTopicType()
     );
  }

  public static class RosConnectionKind extends TagKind {
    public static final RosConnectionKind INSTANCE = new RosConnectionKind();

    protected RosConnectionKind() {
    }
  }
}