/* generated by template templates.de.monticore.lang.tagschema.TagSchema*/


package nfp.RosToEmamTagSchema;

import de.monticore.lang.tagging._symboltable.TaggingResolver;
import de.monticore.symboltable.resolving.CommonResolvingFilter;

/**
 * generated by TagSchema.ftl
 */
public class RosToEmamTagSchema {

  protected static RosToEmamTagSchema instance = null;

  protected RosToEmamTagSchema() {}

  protected static RosToEmamTagSchema getInstance() {
    if (instance == null) {
      instance = new RosToEmamTagSchema();
    }
    return instance;
  }

  protected void doRegisterTagTypes(TaggingResolver tagging) {
    tagging.addTagSymbolCreator(new RosConnectionSymbolCreator());
    tagging.addTagSymbolResolvingFilter(CommonResolvingFilter.create(RosConnectionSymbol.KIND));
  }

  public static void registerTagTypes(TaggingResolver tagging) {
    getInstance().doRegisterTagTypes(tagging);
  }

}