/* generated by template templates.de.monticore.lang.tagschema.ComplexTagType*/


package nfp.PhysicalTags;

import de.monticore.lang.tagging._symboltable.TagKind;
import de.monticore.lang.tagging._symboltable.TagSymbol;

import org.jscience.physics.amount.Amount;
import javax.measure.quantity.*;

/**
 * Created by ValuedTagType.ftl
 */
public class SizeSymbol extends TagSymbol {
  public static final SizeKind KIND = SizeKind.INSTANCE;

  public SizeSymbol(
    Amount<?> width,
    Amount<?> depth,
    Amount<?> height
  ) {
    super(KIND,
    (Amount<Length>)width,
    (Amount<Length>)depth,
    (Amount<Length>)height
    );
  }

  public Amount<Length> getWidth() {
    return getValue(0);
  }

  public Amount<Length> getDepth() {
    return getValue(1);
  }

  public Amount<Length> getHeight() {
    return getValue(2);
  }


  @Override
  public String toString() {
    return String.format("Size = " +
    "%s"+
    "%s"+
    "%s"
    ,
    getWidth(),
    getDepth(),
    getHeight()
     );
  }

  public static class SizeKind extends TagKind {
    public static final SizeKind INSTANCE = new SizeKind();

    protected SizeKind() {
    }
  }
}