// (c) https://github.com/MontiCore/monticore
/* generated from model SD4ComponentTesting */
/* generated by template core.Class*/

/* (c) https://github.com/MontiCore/monticore */
package montithings.tools.sd4componenttesting._symboltable;

import arcbasis._symboltable.ComponentTypeSymbol;

public   class SD4ComponentTestingArtifactScope extends SD4ComponentTestingArtifactScopeTOP {
  protected ComponentTypeSymbol mainComponentTypeSymbol;

  public ComponentTypeSymbol getMainComponentTypeSymbol() {
    return mainComponentTypeSymbol;
  }

  public void setMainComponentTypeSymbol(ComponentTypeSymbol mainComponentTypeSymbol) {
    this.mainComponentTypeSymbol = mainComponentTypeSymbol;
  }
}
