// (c) https://github.com/MontiCore/monticore

// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_DDSRECORDERMESSAGETYPESUPPORTC_H_
#define _TAO_IDL_DDSRECORDERMESSAGETYPESUPPORTC_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "DDSRecorderMessageC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDSRecorderMessage
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DDSRecorderMessage::Message, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> MessageSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_MESSAGETYPESUPPORT__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_MESSAGETYPESUPPORT__VAR_OUT_CH_

  class MessageTypeSupport;
  typedef MessageTypeSupport *MessageTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        MessageTypeSupport
      >
    MessageTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        MessageTypeSupport
      >
    MessageTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MessageTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MessageTypeSupport_ptr _ptr_type;
    typedef MessageTypeSupport_var _var_type;
    typedef MessageTypeSupport_out _out_type;

    // The static operations.
    static MessageTypeSupport_ptr _duplicate (MessageTypeSupport_ptr obj);

    static void _tao_release (MessageTypeSupport_ptr obj);

    static MessageTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static MessageTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MessageTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MessageTypeSupport (void);

    

    virtual ~MessageTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (MessageTypeSupport (const MessageTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (MessageTypeSupport (MessageTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (MessageTypeSupport &operator= (const MessageTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (MessageTypeSupport &operator= (MessageTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_MESSAGEDATAWRITER__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_MESSAGEDATAWRITER__VAR_OUT_CH_

  class MessageDataWriter;
  typedef MessageDataWriter *MessageDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        MessageDataWriter
      >
    MessageDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        MessageDataWriter
      >
    MessageDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MessageDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MessageDataWriter_ptr _ptr_type;
    typedef MessageDataWriter_var _var_type;
    typedef MessageDataWriter_out _out_type;

    // The static operations.
    static MessageDataWriter_ptr _duplicate (MessageDataWriter_ptr obj);

    static void _tao_release (MessageDataWriter_ptr obj);

    static MessageDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static MessageDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MessageDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DDSRecorderMessage::Message & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DDSRecorderMessage::Message & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DDSRecorderMessage::Message & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DDSRecorderMessage::Message & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DDSRecorderMessage::Message & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDSRecorderMessage::Message & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DDSRecorderMessage::Message & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDSRecorderMessage::Message & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSRecorderMessage::Message & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSRecorderMessage::Message & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MessageDataWriter (void);

    

    virtual ~MessageDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (MessageDataWriter (const MessageDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (MessageDataWriter (MessageDataWriter &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (MessageDataWriter &operator= (const MessageDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (MessageDataWriter &operator= (MessageDataWriter &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_MESSAGEDATAREADER__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_MESSAGEDATAREADER__VAR_OUT_CH_

  class MessageDataReader;
  typedef MessageDataReader *MessageDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        MessageDataReader
      >
    MessageDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        MessageDataReader
      >
    MessageDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MessageDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MessageDataReader_ptr _ptr_type;
    typedef MessageDataReader_var _var_type;
    typedef MessageDataReader_out _out_type;

    // The static operations.
    static MessageDataReader_ptr _duplicate (MessageDataReader_ptr obj);

    static void _tao_release (MessageDataReader_ptr obj);

    static MessageDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static MessageDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MessageDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::DDSRecorderMessage::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DDSRecorderMessage::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DDSRecorderMessage::MessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DDSRecorderMessage::MessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDSRecorderMessage::Message & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDSRecorderMessage::Message & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DDSRecorderMessage::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DDSRecorderMessage::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DDSRecorderMessage::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DDSRecorderMessage::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DDSRecorderMessage::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DDSRecorderMessage::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DDSRecorderMessage::MessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DDSRecorderMessage::MessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DDSRecorderMessage::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSRecorderMessage::Message & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSRecorderMessage::Message & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MessageDataReader (void);

    

    virtual ~MessageDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (MessageDataReader (const MessageDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (MessageDataReader (MessageDataReader &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (MessageDataReader &operator= (const MessageDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (MessageDataReader &operator= (MessageDataReader &&))
#endif /* ACE_HAS_CPP11 */
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDSRecorderMessage

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDSRecorderMessage
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DDSRecorderMessage::Command, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> CommandSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_COMMANDTYPESUPPORT__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_COMMANDTYPESUPPORT__VAR_OUT_CH_

  class CommandTypeSupport;
  typedef CommandTypeSupport *CommandTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        CommandTypeSupport
      >
    CommandTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        CommandTypeSupport
      >
    CommandTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  CommandTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef CommandTypeSupport_ptr _ptr_type;
    typedef CommandTypeSupport_var _var_type;
    typedef CommandTypeSupport_out _out_type;

    // The static operations.
    static CommandTypeSupport_ptr _duplicate (CommandTypeSupport_ptr obj);

    static void _tao_release (CommandTypeSupport_ptr obj);

    static CommandTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static CommandTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static CommandTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    CommandTypeSupport (void);

    

    virtual ~CommandTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (CommandTypeSupport (const CommandTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandTypeSupport (CommandTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (CommandTypeSupport &operator= (const CommandTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandTypeSupport &operator= (CommandTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_COMMANDDATAWRITER__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_COMMANDDATAWRITER__VAR_OUT_CH_

  class CommandDataWriter;
  typedef CommandDataWriter *CommandDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        CommandDataWriter
      >
    CommandDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        CommandDataWriter
      >
    CommandDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  CommandDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef CommandDataWriter_ptr _ptr_type;
    typedef CommandDataWriter_var _var_type;
    typedef CommandDataWriter_out _out_type;

    // The static operations.
    static CommandDataWriter_ptr _duplicate (CommandDataWriter_ptr obj);

    static void _tao_release (CommandDataWriter_ptr obj);

    static CommandDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static CommandDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static CommandDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DDSRecorderMessage::Command & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DDSRecorderMessage::Command & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DDSRecorderMessage::Command & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DDSRecorderMessage::Command & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DDSRecorderMessage::Command & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDSRecorderMessage::Command & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DDSRecorderMessage::Command & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDSRecorderMessage::Command & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSRecorderMessage::Command & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSRecorderMessage::Command & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    CommandDataWriter (void);

    

    virtual ~CommandDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (CommandDataWriter (const CommandDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandDataWriter (CommandDataWriter &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (CommandDataWriter &operator= (const CommandDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandDataWriter &operator= (CommandDataWriter &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_COMMANDDATAREADER__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_COMMANDDATAREADER__VAR_OUT_CH_

  class CommandDataReader;
  typedef CommandDataReader *CommandDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        CommandDataReader
      >
    CommandDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        CommandDataReader
      >
    CommandDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  CommandDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef CommandDataReader_ptr _ptr_type;
    typedef CommandDataReader_var _var_type;
    typedef CommandDataReader_out _out_type;

    // The static operations.
    static CommandDataReader_ptr _duplicate (CommandDataReader_ptr obj);

    static void _tao_release (CommandDataReader_ptr obj);

    static CommandDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static CommandDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static CommandDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::DDSRecorderMessage::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DDSRecorderMessage::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DDSRecorderMessage::CommandSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DDSRecorderMessage::CommandSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDSRecorderMessage::Command & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDSRecorderMessage::Command & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DDSRecorderMessage::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DDSRecorderMessage::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DDSRecorderMessage::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DDSRecorderMessage::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DDSRecorderMessage::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DDSRecorderMessage::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DDSRecorderMessage::CommandSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DDSRecorderMessage::CommandSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DDSRecorderMessage::CommandSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSRecorderMessage::Command & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSRecorderMessage::Command & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    CommandDataReader (void);

    

    virtual ~CommandDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (CommandDataReader (const CommandDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandDataReader (CommandDataReader &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (CommandDataReader &operator= (const CommandDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandDataReader &operator= (CommandDataReader &&))
#endif /* ACE_HAS_CPP11 */
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDSRecorderMessage

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDSRecorderMessage
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DDSRecorderMessage::CommandReply, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> CommandReplySeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_COMMANDREPLYTYPESUPPORT__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_COMMANDREPLYTYPESUPPORT__VAR_OUT_CH_

  class CommandReplyTypeSupport;
  typedef CommandReplyTypeSupport *CommandReplyTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        CommandReplyTypeSupport
      >
    CommandReplyTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        CommandReplyTypeSupport
      >
    CommandReplyTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  CommandReplyTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef CommandReplyTypeSupport_ptr _ptr_type;
    typedef CommandReplyTypeSupport_var _var_type;
    typedef CommandReplyTypeSupport_out _out_type;

    // The static operations.
    static CommandReplyTypeSupport_ptr _duplicate (CommandReplyTypeSupport_ptr obj);

    static void _tao_release (CommandReplyTypeSupport_ptr obj);

    static CommandReplyTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static CommandReplyTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static CommandReplyTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    CommandReplyTypeSupport (void);

    

    virtual ~CommandReplyTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (CommandReplyTypeSupport (const CommandReplyTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandReplyTypeSupport (CommandReplyTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (CommandReplyTypeSupport &operator= (const CommandReplyTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandReplyTypeSupport &operator= (CommandReplyTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_COMMANDREPLYDATAWRITER__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_COMMANDREPLYDATAWRITER__VAR_OUT_CH_

  class CommandReplyDataWriter;
  typedef CommandReplyDataWriter *CommandReplyDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        CommandReplyDataWriter
      >
    CommandReplyDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        CommandReplyDataWriter
      >
    CommandReplyDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  CommandReplyDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef CommandReplyDataWriter_ptr _ptr_type;
    typedef CommandReplyDataWriter_var _var_type;
    typedef CommandReplyDataWriter_out _out_type;

    // The static operations.
    static CommandReplyDataWriter_ptr _duplicate (CommandReplyDataWriter_ptr obj);

    static void _tao_release (CommandReplyDataWriter_ptr obj);

    static CommandReplyDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static CommandReplyDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static CommandReplyDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DDSRecorderMessage::CommandReply & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DDSRecorderMessage::CommandReply & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DDSRecorderMessage::CommandReply & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DDSRecorderMessage::CommandReply & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DDSRecorderMessage::CommandReply & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDSRecorderMessage::CommandReply & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DDSRecorderMessage::CommandReply & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDSRecorderMessage::CommandReply & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSRecorderMessage::CommandReply & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSRecorderMessage::CommandReply & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    CommandReplyDataWriter (void);

    

    virtual ~CommandReplyDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (CommandReplyDataWriter (const CommandReplyDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandReplyDataWriter (CommandReplyDataWriter &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (CommandReplyDataWriter &operator= (const CommandReplyDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandReplyDataWriter &operator= (CommandReplyDataWriter &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_COMMANDREPLYDATAREADER__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_COMMANDREPLYDATAREADER__VAR_OUT_CH_

  class CommandReplyDataReader;
  typedef CommandReplyDataReader *CommandReplyDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        CommandReplyDataReader
      >
    CommandReplyDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        CommandReplyDataReader
      >
    CommandReplyDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  CommandReplyDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef CommandReplyDataReader_ptr _ptr_type;
    typedef CommandReplyDataReader_var _var_type;
    typedef CommandReplyDataReader_out _out_type;

    // The static operations.
    static CommandReplyDataReader_ptr _duplicate (CommandReplyDataReader_ptr obj);

    static void _tao_release (CommandReplyDataReader_ptr obj);

    static CommandReplyDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static CommandReplyDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static CommandReplyDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::DDSRecorderMessage::CommandReplySeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DDSRecorderMessage::CommandReplySeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DDSRecorderMessage::CommandReplySeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DDSRecorderMessage::CommandReplySeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDSRecorderMessage::CommandReply & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDSRecorderMessage::CommandReply & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DDSRecorderMessage::CommandReplySeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DDSRecorderMessage::CommandReplySeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DDSRecorderMessage::CommandReplySeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DDSRecorderMessage::CommandReplySeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DDSRecorderMessage::CommandReplySeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DDSRecorderMessage::CommandReplySeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DDSRecorderMessage::CommandReplySeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DDSRecorderMessage::CommandReplySeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DDSRecorderMessage::CommandReplySeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSRecorderMessage::CommandReply & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSRecorderMessage::CommandReply & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    CommandReplyDataReader (void);

    

    virtual ~CommandReplyDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (CommandReplyDataReader (const CommandReplyDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandReplyDataReader (CommandReplyDataReader &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (CommandReplyDataReader &operator= (const CommandReplyDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (CommandReplyDataReader &operator= (CommandReplyDataReader &&))
#endif /* ACE_HAS_CPP11 */
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDSRecorderMessage

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace DDSRecorderMessage
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DDSRecorderMessage::Acknowledgement, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> AcknowledgementSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_ACKNOWLEDGEMENTTYPESUPPORT__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_ACKNOWLEDGEMENTTYPESUPPORT__VAR_OUT_CH_

  class AcknowledgementTypeSupport;
  typedef AcknowledgementTypeSupport *AcknowledgementTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        AcknowledgementTypeSupport
      >
    AcknowledgementTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        AcknowledgementTypeSupport
      >
    AcknowledgementTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  AcknowledgementTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef AcknowledgementTypeSupport_ptr _ptr_type;
    typedef AcknowledgementTypeSupport_var _var_type;
    typedef AcknowledgementTypeSupport_out _out_type;

    // The static operations.
    static AcknowledgementTypeSupport_ptr _duplicate (AcknowledgementTypeSupport_ptr obj);

    static void _tao_release (AcknowledgementTypeSupport_ptr obj);

    static AcknowledgementTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static AcknowledgementTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static AcknowledgementTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    AcknowledgementTypeSupport (void);

    

    virtual ~AcknowledgementTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementTypeSupport (const AcknowledgementTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementTypeSupport (AcknowledgementTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementTypeSupport &operator= (const AcknowledgementTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementTypeSupport &operator= (AcknowledgementTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_ACKNOWLEDGEMENTDATAWRITER__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_ACKNOWLEDGEMENTDATAWRITER__VAR_OUT_CH_

  class AcknowledgementDataWriter;
  typedef AcknowledgementDataWriter *AcknowledgementDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        AcknowledgementDataWriter
      >
    AcknowledgementDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        AcknowledgementDataWriter
      >
    AcknowledgementDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  AcknowledgementDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef AcknowledgementDataWriter_ptr _ptr_type;
    typedef AcknowledgementDataWriter_var _var_type;
    typedef AcknowledgementDataWriter_out _out_type;

    // The static operations.
    static AcknowledgementDataWriter_ptr _duplicate (AcknowledgementDataWriter_ptr obj);

    static void _tao_release (AcknowledgementDataWriter_ptr obj);

    static AcknowledgementDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static AcknowledgementDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static AcknowledgementDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DDSRecorderMessage::Acknowledgement & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DDSRecorderMessage::Acknowledgement & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DDSRecorderMessage::Acknowledgement & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DDSRecorderMessage::Acknowledgement & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DDSRecorderMessage::Acknowledgement & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDSRecorderMessage::Acknowledgement & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DDSRecorderMessage::Acknowledgement & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDSRecorderMessage::Acknowledgement & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSRecorderMessage::Acknowledgement & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSRecorderMessage::Acknowledgement & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    AcknowledgementDataWriter (void);

    

    virtual ~AcknowledgementDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementDataWriter (const AcknowledgementDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementDataWriter (AcknowledgementDataWriter &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementDataWriter &operator= (const AcknowledgementDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementDataWriter &operator= (AcknowledgementDataWriter &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_DDSRECORDERMESSAGE_ACKNOWLEDGEMENTDATAREADER__VAR_OUT_CH_)
#define _DDSRECORDERMESSAGE_ACKNOWLEDGEMENTDATAREADER__VAR_OUT_CH_

  class AcknowledgementDataReader;
  typedef AcknowledgementDataReader *AcknowledgementDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        AcknowledgementDataReader
      >
    AcknowledgementDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        AcknowledgementDataReader
      >
    AcknowledgementDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  AcknowledgementDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef AcknowledgementDataReader_ptr _ptr_type;
    typedef AcknowledgementDataReader_var _var_type;
    typedef AcknowledgementDataReader_out _out_type;

    // The static operations.
    static AcknowledgementDataReader_ptr _duplicate (AcknowledgementDataReader_ptr obj);

    static void _tao_release (AcknowledgementDataReader_ptr obj);

    static AcknowledgementDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static AcknowledgementDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static AcknowledgementDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::DDSRecorderMessage::AcknowledgementSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DDSRecorderMessage::AcknowledgementSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DDSRecorderMessage::AcknowledgementSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DDSRecorderMessage::AcknowledgementSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDSRecorderMessage::Acknowledgement & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDSRecorderMessage::Acknowledgement & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DDSRecorderMessage::AcknowledgementSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DDSRecorderMessage::AcknowledgementSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DDSRecorderMessage::AcknowledgementSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DDSRecorderMessage::AcknowledgementSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DDSRecorderMessage::AcknowledgementSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DDSRecorderMessage::AcknowledgementSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DDSRecorderMessage::AcknowledgementSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DDSRecorderMessage::AcknowledgementSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DDSRecorderMessage::AcknowledgementSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSRecorderMessage::Acknowledgement & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSRecorderMessage::Acknowledgement & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    AcknowledgementDataReader (void);

    

    virtual ~AcknowledgementDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementDataReader (const AcknowledgementDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementDataReader (AcknowledgementDataReader &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementDataReader &operator= (const AcknowledgementDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (AcknowledgementDataReader &operator= (AcknowledgementDataReader &&))
#endif /* ACE_HAS_CPP11 */
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module DDSRecorderMessage

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DDSRECORDERMESSAGE_MESSAGETYPESUPPORT__TRAITS_)
#define _DDSRECORDERMESSAGE_MESSAGETYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::MessageTypeSupport>
  {
    static ::DDSRecorderMessage::MessageTypeSupport_ptr duplicate (
        ::DDSRecorderMessage::MessageTypeSupport_ptr p);
    static void release (
        ::DDSRecorderMessage::MessageTypeSupport_ptr p);
    static ::DDSRecorderMessage::MessageTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::MessageTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_MESSAGEDATAWRITER__TRAITS_)
#define _DDSRECORDERMESSAGE_MESSAGEDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::MessageDataWriter>
  {
    static ::DDSRecorderMessage::MessageDataWriter_ptr duplicate (
        ::DDSRecorderMessage::MessageDataWriter_ptr p);
    static void release (
        ::DDSRecorderMessage::MessageDataWriter_ptr p);
    static ::DDSRecorderMessage::MessageDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::MessageDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_MESSAGEDATAREADER__TRAITS_)
#define _DDSRECORDERMESSAGE_MESSAGEDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::MessageDataReader>
  {
    static ::DDSRecorderMessage::MessageDataReader_ptr duplicate (
        ::DDSRecorderMessage::MessageDataReader_ptr p);
    static void release (
        ::DDSRecorderMessage::MessageDataReader_ptr p);
    static ::DDSRecorderMessage::MessageDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::MessageDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_COMMANDTYPESUPPORT__TRAITS_)
#define _DDSRECORDERMESSAGE_COMMANDTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::CommandTypeSupport>
  {
    static ::DDSRecorderMessage::CommandTypeSupport_ptr duplicate (
        ::DDSRecorderMessage::CommandTypeSupport_ptr p);
    static void release (
        ::DDSRecorderMessage::CommandTypeSupport_ptr p);
    static ::DDSRecorderMessage::CommandTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::CommandTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_COMMANDDATAWRITER__TRAITS_)
#define _DDSRECORDERMESSAGE_COMMANDDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::CommandDataWriter>
  {
    static ::DDSRecorderMessage::CommandDataWriter_ptr duplicate (
        ::DDSRecorderMessage::CommandDataWriter_ptr p);
    static void release (
        ::DDSRecorderMessage::CommandDataWriter_ptr p);
    static ::DDSRecorderMessage::CommandDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::CommandDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_COMMANDDATAREADER__TRAITS_)
#define _DDSRECORDERMESSAGE_COMMANDDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::CommandDataReader>
  {
    static ::DDSRecorderMessage::CommandDataReader_ptr duplicate (
        ::DDSRecorderMessage::CommandDataReader_ptr p);
    static void release (
        ::DDSRecorderMessage::CommandDataReader_ptr p);
    static ::DDSRecorderMessage::CommandDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::CommandDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_COMMANDREPLYTYPESUPPORT__TRAITS_)
#define _DDSRECORDERMESSAGE_COMMANDREPLYTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::CommandReplyTypeSupport>
  {
    static ::DDSRecorderMessage::CommandReplyTypeSupport_ptr duplicate (
        ::DDSRecorderMessage::CommandReplyTypeSupport_ptr p);
    static void release (
        ::DDSRecorderMessage::CommandReplyTypeSupport_ptr p);
    static ::DDSRecorderMessage::CommandReplyTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::CommandReplyTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_COMMANDREPLYDATAWRITER__TRAITS_)
#define _DDSRECORDERMESSAGE_COMMANDREPLYDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::CommandReplyDataWriter>
  {
    static ::DDSRecorderMessage::CommandReplyDataWriter_ptr duplicate (
        ::DDSRecorderMessage::CommandReplyDataWriter_ptr p);
    static void release (
        ::DDSRecorderMessage::CommandReplyDataWriter_ptr p);
    static ::DDSRecorderMessage::CommandReplyDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::CommandReplyDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_COMMANDREPLYDATAREADER__TRAITS_)
#define _DDSRECORDERMESSAGE_COMMANDREPLYDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::CommandReplyDataReader>
  {
    static ::DDSRecorderMessage::CommandReplyDataReader_ptr duplicate (
        ::DDSRecorderMessage::CommandReplyDataReader_ptr p);
    static void release (
        ::DDSRecorderMessage::CommandReplyDataReader_ptr p);
    static ::DDSRecorderMessage::CommandReplyDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::CommandReplyDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_ACKNOWLEDGEMENTTYPESUPPORT__TRAITS_)
#define _DDSRECORDERMESSAGE_ACKNOWLEDGEMENTTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::AcknowledgementTypeSupport>
  {
    static ::DDSRecorderMessage::AcknowledgementTypeSupport_ptr duplicate (
        ::DDSRecorderMessage::AcknowledgementTypeSupport_ptr p);
    static void release (
        ::DDSRecorderMessage::AcknowledgementTypeSupport_ptr p);
    static ::DDSRecorderMessage::AcknowledgementTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::AcknowledgementTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_ACKNOWLEDGEMENTDATAWRITER__TRAITS_)
#define _DDSRECORDERMESSAGE_ACKNOWLEDGEMENTDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::AcknowledgementDataWriter>
  {
    static ::DDSRecorderMessage::AcknowledgementDataWriter_ptr duplicate (
        ::DDSRecorderMessage::AcknowledgementDataWriter_ptr p);
    static void release (
        ::DDSRecorderMessage::AcknowledgementDataWriter_ptr p);
    static ::DDSRecorderMessage::AcknowledgementDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::AcknowledgementDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSRECORDERMESSAGE_ACKNOWLEDGEMENTDATAREADER__TRAITS_)
#define _DDSRECORDERMESSAGE_ACKNOWLEDGEMENTDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSRecorderMessage::AcknowledgementDataReader>
  {
    static ::DDSRecorderMessage::AcknowledgementDataReader_ptr duplicate (
        ::DDSRecorderMessage::AcknowledgementDataReader_ptr p);
    static void release (
        ::DDSRecorderMessage::AcknowledgementDataReader_ptr p);
    static ::DDSRecorderMessage::AcknowledgementDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DDSRecorderMessage::AcknowledgementDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "DDSRecorderMessageTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

