/* generated by template templates.de.monticore.lang.tagschema.ValuedTagType*/


package montiarc.tagging.distribution;

import de.monticore.lang.tagging._symboltable.TagKind;
import de.monticore.lang.tagging._symboltable.TagSymbol;


/**
 * Symbol table entry for Connections specified in tagged models.
 */
public class ConnectionSymbol extends TagSymbol {
  public static final ConnectionKind KIND = ConnectionKind.INSTANCE;

  public ConnectionSymbol(String value) {
    super(KIND, value);
  }

  protected ConnectionSymbol(ConnectionKind kind, String value) {
    super(kind, value);
  }

  public String getValue() {
     return getValue(0);
  }

  @Override
  public String toString() {
    return String.format("Connection = \"%s\"",
      getValue().toString());
  }

  public static class ConnectionKind extends TagKind {
    public static final ConnectionKind INSTANCE = new ConnectionKind();

    protected ConnectionKind() {
    }
  }
}