/* generated by template templates.de.monticore.lang.tagschema.TagSchema*/


package nfp.OCL2JavaTags;

import de.monticore.lang.tagging._symboltable.TaggingResolver;
import de.monticore.symboltable.resolving.CommonResolvingFilter;

/**
 * generated by TagSchema.ftl
 */
public class OCL2JavaTags {

  protected static OCL2JavaTags instance = null;

  protected OCL2JavaTags() {}

  protected static OCL2JavaTags getInstance() {
    if (instance == null) {
      instance = new OCL2JavaTags();
    }
    return instance;
  }

  protected void doRegisterTagTypes(TaggingResolver tagging) {
    tagging.addTagSymbolCreator(new SymbolNameSymbolCreator());
    tagging.addTagSymbolResolvingFilter(CommonResolvingFilter.create(SymbolNameSymbol.KIND));
  }

  public static void registerTagTypes(TaggingResolver tagging) {
    getInstance().doRegisterTagTypes(tagging);
  }

}