/* generated by template templates.de.monticore.lang.tagschema.ValuedTagType*/


package nfp.OCL2JavaTags;

import de.monticore.lang.tagging._symboltable.TagKind;
import de.monticore.lang.tagging._symboltable.TagSymbol;


/**
 * Created by ValuedTagType.ftl
 */
public class SymbolNameSymbol extends TagSymbol {
  public static final SymbolNameKind KIND = SymbolNameKind.INSTANCE;

  public SymbolNameSymbol(String value) {
    super(KIND, value);
  }

  protected SymbolNameSymbol(SymbolNameKind kind, String value) {
    super(kind, value);
  }

  public String getValue() {
     return getValue(0);
  }

  @Override
  public String toString() {
    return String.format("SymbolName = \"%s\"",
      getValue().toString());
  }

  public static class SymbolNameKind extends TagKind {
    public static final SymbolNameKind INSTANCE = new SymbolNameKind();

    protected SymbolNameKind() {
    }
  }
}