/* generated by template templates.de.monticore.lang.tagschema.TagSchema*/


package nfp.CompPower;

import de.monticore.lang.tagging._symboltable.TaggingResolver;
import de.monticore.symboltable.resolving.CommonResolvingFilter;

/**
 * generated by TagSchema.ftl
 */
public class CompPower {

  protected static CompPower instance = null;

  protected CompPower() {}

  protected static CompPower getInstance() {
    if (instance == null) {
      instance = new CompPower();
    }
    return instance;
  }

  protected void doRegisterTagTypes(TaggingResolver tagging) {
    tagging.addTagSymbolCreator(new CompPowerInstSymbolCreator());
    tagging.addTagSymbolResolvingFilter(CommonResolvingFilter.create(CompPowerInstSymbol.KIND));
    tagging.addTagSymbolCreator(new CompPowerSymbolCreator());
    tagging.addTagSymbolResolvingFilter(CommonResolvingFilter.create(CompPowerSymbol.KIND));
  }

  public static void registerTagTypes(TaggingResolver tagging) {
    getInstance().doRegisterTagTypes(tagging);
  }

}