/* generated by template templates.de.monticore.lang.tagschema.TagSchema*/


package nfp.Distribution;

import de.monticore.lang.tagging._symboltable.TaggingResolver;
import de.monticore.symboltable.resolving.CommonResolvingFilter;

/**
 * generated by TagSchema.ftl
 */
public class Distribution {

  protected static Distribution instance = null;

  protected Distribution() {}

  protected static Distribution getInstance() {
    if (instance == null) {
      instance = new Distribution();
    }
    return instance;
  }

  protected void doRegisterTagTypes(TaggingResolver tagging) {
    tagging.addTagSymbolCreator(new ConnectionSymbolCreator());
    tagging.addTagSymbolResolvingFilter(CommonResolvingFilter.create(ConnectionSymbol.KIND));
  }

  public static void registerTagTypes(TaggingResolver tagging) {
    getInstance().doRegisterTagTypes(tagging);
  }

}