% (c) https://github.com/MontiCore/monticore
% generated by template templates/query.ftl
:- include('facts').
:- include('helpers').

get_distribution_Droom_temp_sensor_latest(Droom_temp_sensor_latest) :-
    get_available_devices(AllAvailableDevices),

    % apply device properties that have to be matched
    include(property(state,online),AllAvailableDevices,AllAvailableDevicesFiltered1),
    include(property(has_hardware,sensor_temperature),AllAvailableDevicesFiltered1,AllAvailableDevicesFiltered2),

    % apply distribution constraints
    % first constrains equal: ==
    include_equal(property(location, building1_floor1), 1, AllAvailableDevicesFiltered2,AllAvailableDevicesFiltered3),
    include_equal(property(location, building2_floor1), 1, AllAvailableDevicesFiltered3,AllAvailableDevicesFiltered4),
    include_equal(property(location, building3_floor1), 1, AllAvailableDevicesFiltered4,AllAvailableDevicesFiltered5),
    include_equal(property(location, building1_floor2), 1, AllAvailableDevicesFiltered5,AllAvailableDevicesFiltered6),
    include_equal(property(location, building2_floor2), 1, AllAvailableDevicesFiltered6,AllAvailableDevicesFiltered7),
    include_equal(property(location, building3_floor2), 1, AllAvailableDevicesFiltered7,AllAvailableDevicesFiltered8),
    include_equal(property(location, floor3), 0, AllAvailableDevicesFiltered8,AllAvailableDevicesFiltered9),

    % then constrains less than equal: =<

    % then constrains greater than equal: >=

    % then constrains that check all equal

    % bind result to target variable
    AllAvailableDevicesFiltered9 = Droom_temp_sensor_latest.


distribution(Droom_temp_sensor_latest) :-
    % retrieve possible lists of devices
    get_distribution_Droom_temp_sensor_latest(Droom_temp_sensor_latest),

    % apply incompatible checks

    % apply dependency checks
    % finishing query with a .
    1 == 1.
