apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iot-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iot-binding
subjects:
- kind: ServiceAccount
  name: iot
  namespace: default
roleRef:
  kind: ClusterRole
  name: iot-role
  apiGroup: rbac.authorization.k8s.io
