// (c) https://github.com/MontiCore/monticore

// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "DDSLogTracerMessageTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "DDSLogTracerMessageTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for DDSLogTracerMessage::RequestTypeSupport.

DDSLogTracerMessage::RequestTypeSupport_ptr
TAO::Objref_Traits<DDSLogTracerMessage::RequestTypeSupport>::duplicate (
    DDSLogTracerMessage::RequestTypeSupport_ptr p)
{
  return DDSLogTracerMessage::RequestTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<DDSLogTracerMessage::RequestTypeSupport>::release (
    DDSLogTracerMessage::RequestTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

DDSLogTracerMessage::RequestTypeSupport_ptr
TAO::Objref_Traits<DDSLogTracerMessage::RequestTypeSupport>::nil (void)
{
  return DDSLogTracerMessage::RequestTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DDSLogTracerMessage::RequestTypeSupport>::marshal (
    const DDSLogTracerMessage::RequestTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DDSLogTracerMessage::RequestTypeSupport::RequestTypeSupport (void)
{}

DDSLogTracerMessage::RequestTypeSupport::~RequestTypeSupport (void)
{
}

DDSLogTracerMessage::RequestTypeSupport_ptr
DDSLogTracerMessage::RequestTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RequestTypeSupport::_duplicate (
      dynamic_cast<RequestTypeSupport_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::RequestTypeSupport_ptr
DDSLogTracerMessage::RequestTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RequestTypeSupport::_duplicate (
      dynamic_cast<RequestTypeSupport_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::RequestTypeSupport_ptr
DDSLogTracerMessage::RequestTypeSupport::_nil (void)
{
  return 0;
}

DDSLogTracerMessage::RequestTypeSupport_ptr
DDSLogTracerMessage::RequestTypeSupport::_duplicate (RequestTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DDSLogTracerMessage::RequestTypeSupport::_tao_release (RequestTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DDSLogTracerMessage::RequestTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDSLogTracerMessage/RequestTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DDSLogTracerMessage::RequestTypeSupport::_interface_repository_id (void) const
{
  return "IDL:DDSLogTracerMessage/RequestTypeSupport:1.0";
}

::CORBA::Boolean
DDSLogTracerMessage::RequestTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for DDSLogTracerMessage::RequestDataWriter.

DDSLogTracerMessage::RequestDataWriter_ptr
TAO::Objref_Traits<DDSLogTracerMessage::RequestDataWriter>::duplicate (
    DDSLogTracerMessage::RequestDataWriter_ptr p)
{
  return DDSLogTracerMessage::RequestDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<DDSLogTracerMessage::RequestDataWriter>::release (
    DDSLogTracerMessage::RequestDataWriter_ptr p)
{
  ::CORBA::release (p);
}

DDSLogTracerMessage::RequestDataWriter_ptr
TAO::Objref_Traits<DDSLogTracerMessage::RequestDataWriter>::nil (void)
{
  return DDSLogTracerMessage::RequestDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DDSLogTracerMessage::RequestDataWriter>::marshal (
    const DDSLogTracerMessage::RequestDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DDSLogTracerMessage::RequestDataWriter::RequestDataWriter (void)
{}

DDSLogTracerMessage::RequestDataWriter::~RequestDataWriter (void)
{
}

DDSLogTracerMessage::RequestDataWriter_ptr
DDSLogTracerMessage::RequestDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RequestDataWriter::_duplicate (
      dynamic_cast<RequestDataWriter_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::RequestDataWriter_ptr
DDSLogTracerMessage::RequestDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RequestDataWriter::_duplicate (
      dynamic_cast<RequestDataWriter_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::RequestDataWriter_ptr
DDSLogTracerMessage::RequestDataWriter::_nil (void)
{
  return 0;
}

DDSLogTracerMessage::RequestDataWriter_ptr
DDSLogTracerMessage::RequestDataWriter::_duplicate (RequestDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DDSLogTracerMessage::RequestDataWriter::_tao_release (RequestDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DDSLogTracerMessage::RequestDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDSLogTracerMessage/RequestDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DDSLogTracerMessage::RequestDataWriter::_interface_repository_id (void) const
{
  return "IDL:DDSLogTracerMessage/RequestDataWriter:1.0";
}

::CORBA::Boolean
DDSLogTracerMessage::RequestDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for DDSLogTracerMessage::RequestDataReader.

DDSLogTracerMessage::RequestDataReader_ptr
TAO::Objref_Traits<DDSLogTracerMessage::RequestDataReader>::duplicate (
    DDSLogTracerMessage::RequestDataReader_ptr p)
{
  return DDSLogTracerMessage::RequestDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<DDSLogTracerMessage::RequestDataReader>::release (
    DDSLogTracerMessage::RequestDataReader_ptr p)
{
  ::CORBA::release (p);
}

DDSLogTracerMessage::RequestDataReader_ptr
TAO::Objref_Traits<DDSLogTracerMessage::RequestDataReader>::nil (void)
{
  return DDSLogTracerMessage::RequestDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DDSLogTracerMessage::RequestDataReader>::marshal (
    const DDSLogTracerMessage::RequestDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DDSLogTracerMessage::RequestDataReader::RequestDataReader (void)
{}

DDSLogTracerMessage::RequestDataReader::~RequestDataReader (void)
{
}

DDSLogTracerMessage::RequestDataReader_ptr
DDSLogTracerMessage::RequestDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RequestDataReader::_duplicate (
      dynamic_cast<RequestDataReader_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::RequestDataReader_ptr
DDSLogTracerMessage::RequestDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return RequestDataReader::_duplicate (
      dynamic_cast<RequestDataReader_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::RequestDataReader_ptr
DDSLogTracerMessage::RequestDataReader::_nil (void)
{
  return 0;
}

DDSLogTracerMessage::RequestDataReader_ptr
DDSLogTracerMessage::RequestDataReader::_duplicate (RequestDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DDSLogTracerMessage::RequestDataReader::_tao_release (RequestDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DDSLogTracerMessage::RequestDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDSLogTracerMessage/RequestDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DDSLogTracerMessage::RequestDataReader::_interface_repository_id (void) const
{
  return "IDL:DDSLogTracerMessage/RequestDataReader:1.0";
}

::CORBA::Boolean
DDSLogTracerMessage::RequestDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for DDSLogTracerMessage::ResponseTypeSupport.

DDSLogTracerMessage::ResponseTypeSupport_ptr
TAO::Objref_Traits<DDSLogTracerMessage::ResponseTypeSupport>::duplicate (
    DDSLogTracerMessage::ResponseTypeSupport_ptr p)
{
  return DDSLogTracerMessage::ResponseTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<DDSLogTracerMessage::ResponseTypeSupport>::release (
    DDSLogTracerMessage::ResponseTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

DDSLogTracerMessage::ResponseTypeSupport_ptr
TAO::Objref_Traits<DDSLogTracerMessage::ResponseTypeSupport>::nil (void)
{
  return DDSLogTracerMessage::ResponseTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DDSLogTracerMessage::ResponseTypeSupport>::marshal (
    const DDSLogTracerMessage::ResponseTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DDSLogTracerMessage::ResponseTypeSupport::ResponseTypeSupport (void)
{}

DDSLogTracerMessage::ResponseTypeSupport::~ResponseTypeSupport (void)
{
}

DDSLogTracerMessage::ResponseTypeSupport_ptr
DDSLogTracerMessage::ResponseTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ResponseTypeSupport::_duplicate (
      dynamic_cast<ResponseTypeSupport_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::ResponseTypeSupport_ptr
DDSLogTracerMessage::ResponseTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ResponseTypeSupport::_duplicate (
      dynamic_cast<ResponseTypeSupport_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::ResponseTypeSupport_ptr
DDSLogTracerMessage::ResponseTypeSupport::_nil (void)
{
  return 0;
}

DDSLogTracerMessage::ResponseTypeSupport_ptr
DDSLogTracerMessage::ResponseTypeSupport::_duplicate (ResponseTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DDSLogTracerMessage::ResponseTypeSupport::_tao_release (ResponseTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DDSLogTracerMessage::ResponseTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDSLogTracerMessage/ResponseTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DDSLogTracerMessage::ResponseTypeSupport::_interface_repository_id (void) const
{
  return "IDL:DDSLogTracerMessage/ResponseTypeSupport:1.0";
}

::CORBA::Boolean
DDSLogTracerMessage::ResponseTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for DDSLogTracerMessage::ResponseDataWriter.

DDSLogTracerMessage::ResponseDataWriter_ptr
TAO::Objref_Traits<DDSLogTracerMessage::ResponseDataWriter>::duplicate (
    DDSLogTracerMessage::ResponseDataWriter_ptr p)
{
  return DDSLogTracerMessage::ResponseDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<DDSLogTracerMessage::ResponseDataWriter>::release (
    DDSLogTracerMessage::ResponseDataWriter_ptr p)
{
  ::CORBA::release (p);
}

DDSLogTracerMessage::ResponseDataWriter_ptr
TAO::Objref_Traits<DDSLogTracerMessage::ResponseDataWriter>::nil (void)
{
  return DDSLogTracerMessage::ResponseDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DDSLogTracerMessage::ResponseDataWriter>::marshal (
    const DDSLogTracerMessage::ResponseDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DDSLogTracerMessage::ResponseDataWriter::ResponseDataWriter (void)
{}

DDSLogTracerMessage::ResponseDataWriter::~ResponseDataWriter (void)
{
}

DDSLogTracerMessage::ResponseDataWriter_ptr
DDSLogTracerMessage::ResponseDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ResponseDataWriter::_duplicate (
      dynamic_cast<ResponseDataWriter_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::ResponseDataWriter_ptr
DDSLogTracerMessage::ResponseDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ResponseDataWriter::_duplicate (
      dynamic_cast<ResponseDataWriter_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::ResponseDataWriter_ptr
DDSLogTracerMessage::ResponseDataWriter::_nil (void)
{
  return 0;
}

DDSLogTracerMessage::ResponseDataWriter_ptr
DDSLogTracerMessage::ResponseDataWriter::_duplicate (ResponseDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DDSLogTracerMessage::ResponseDataWriter::_tao_release (ResponseDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DDSLogTracerMessage::ResponseDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDSLogTracerMessage/ResponseDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DDSLogTracerMessage::ResponseDataWriter::_interface_repository_id (void) const
{
  return "IDL:DDSLogTracerMessage/ResponseDataWriter:1.0";
}

::CORBA::Boolean
DDSLogTracerMessage::ResponseDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for DDSLogTracerMessage::ResponseDataReader.

DDSLogTracerMessage::ResponseDataReader_ptr
TAO::Objref_Traits<DDSLogTracerMessage::ResponseDataReader>::duplicate (
    DDSLogTracerMessage::ResponseDataReader_ptr p)
{
  return DDSLogTracerMessage::ResponseDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<DDSLogTracerMessage::ResponseDataReader>::release (
    DDSLogTracerMessage::ResponseDataReader_ptr p)
{
  ::CORBA::release (p);
}

DDSLogTracerMessage::ResponseDataReader_ptr
TAO::Objref_Traits<DDSLogTracerMessage::ResponseDataReader>::nil (void)
{
  return DDSLogTracerMessage::ResponseDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DDSLogTracerMessage::ResponseDataReader>::marshal (
    const DDSLogTracerMessage::ResponseDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DDSLogTracerMessage::ResponseDataReader::ResponseDataReader (void)
{}

DDSLogTracerMessage::ResponseDataReader::~ResponseDataReader (void)
{
}

DDSLogTracerMessage::ResponseDataReader_ptr
DDSLogTracerMessage::ResponseDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ResponseDataReader::_duplicate (
      dynamic_cast<ResponseDataReader_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::ResponseDataReader_ptr
DDSLogTracerMessage::ResponseDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ResponseDataReader::_duplicate (
      dynamic_cast<ResponseDataReader_ptr> (_tao_objref)
    );
}

DDSLogTracerMessage::ResponseDataReader_ptr
DDSLogTracerMessage::ResponseDataReader::_nil (void)
{
  return 0;
}

DDSLogTracerMessage::ResponseDataReader_ptr
DDSLogTracerMessage::ResponseDataReader::_duplicate (ResponseDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DDSLogTracerMessage::ResponseDataReader::_tao_release (ResponseDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DDSLogTracerMessage::ResponseDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDSLogTracerMessage/ResponseDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DDSLogTracerMessage::ResponseDataReader::_interface_repository_id (void) const
{
  return "IDL:DDSLogTracerMessage/ResponseDataReader:1.0";
}

::CORBA::Boolean
DDSLogTracerMessage::ResponseDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

