// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p19
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "DDSLogTracerMessageC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "DDSLogTracerMessageC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_cs.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDSLogTracerMessage::RequestData _tao_enumerator)
{
  return strm << static_cast< ::CORBA::ULong> (_tao_enumerator);
}

::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDSLogTracerMessage::RequestData & _tao_enumerator)
{
  ::CORBA::ULong _tao_temp = 0;
  ::CORBA::Boolean const _tao_success = strm >> _tao_temp;
  
  if (_tao_success)
    {
      _tao_enumerator = static_cast<DDSLogTracerMessage::RequestData> (_tao_temp);
    }
  
  return _tao_success;
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDSLogTracerMessage::Request &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.req_uuid.in ()) &&
    (strm << _tao_aggregate.trace_uuid.in ()) &&
    (strm << _tao_aggregate.from_timestamp) &&
    (strm << _tao_aggregate.req_data);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDSLogTracerMessage::Request &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.req_uuid.out ()) &&
    (strm >> _tao_aggregate.trace_uuid.out ()) &&
    (strm >> _tao_aggregate.from_timestamp) &&
    (strm >> _tao_aggregate.req_data);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_cs.cpp:52

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDSLogTracerMessage::Response &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.req_uuid.in ()) &&
    (strm << _tao_aggregate.req_data) &&
    (strm << _tao_aggregate.content.in ());
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDSLogTracerMessage::Response &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.req_uuid.out ()) &&
    (strm >> _tao_aggregate.req_data) &&
    (strm >> _tao_aggregate.content.out ());
}

TAO_END_VERSIONED_NAMESPACE_DECL



