# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FaceUnlock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x46\x61\x63\x65Unlock.proto\x12\x1fmontithings.FaceUnlock.protobuf\";\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61llowed\x18\x02 \x01(\x08\x12\x12\n\nvisitor_id\x18\x03 \x01(\x05\"\x19\n\x05Image\x12\x10\n\x08personId\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FaceUnlock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=53
  _PERSON._serialized_end=112
  _IMAGE._serialized_start=114
  _IMAGE._serialized_end=139
# @@protoc_insertion_point(module_scope)
