/* generated by template templates.de.monticore.lang.tagschema.ValuedTagType*/


package nfp.LatencyTagSchema;

import de.monticore.lang.tagging._symboltable.TagKind;
import de.monticore.lang.tagging._symboltable.TagSymbol;

import org.jscience.physics.amount.Amount;
import javax.measure.quantity.Duration;
import javax.measure.unit.Unit;

/**
 * Created by ValuedTagType.ftl
 */
public class LatencyConnSymbol extends TagSymbol {
  public static final LatencyConnKind KIND = LatencyConnKind.INSTANCE;

  public LatencyConnSymbol(Amount<Duration> value) {
    this(KIND, value);
  }

  public LatencyConnSymbol(Number number, Unit<Duration> unit) {
    this(KIND, number, unit);
  }

  protected LatencyConnSymbol(LatencyConnKind kind, Amount<Duration> value) {
    super(kind, value);
  }

  protected LatencyConnSymbol(LatencyConnKind kind, Number number, Unit<Duration> unit) {
    this(kind, number.toString().contains(".") ?
      Amount.valueOf(number.doubleValue(), unit) :
      Amount.valueOf(number.intValue(),
          unit));
  }

  public Amount<Duration> getValue() {
     return getValue(0);
  }

  public Number getNumber() {
    return getValue().getExactValue();
  }

  public Unit<Duration> getUnit() {
    return getValue().getUnit();
  }

  @Override
  public String toString() {
    return String.format("LatencyConn = %s %s",
      getNumber(), getUnit());
  }

  public static class LatencyConnKind extends TagKind {
    public static final LatencyConnKind INSTANCE = new LatencyConnKind();

    protected LatencyConnKind() {
    }
  }
}