/* generated from model MontiThings */
/* generated by template ast.AstClass*/

package montithings._ast;


import montiarc._ast.ASTStereotype;

import java.util.Optional;

public class ASTResourcePort extends ASTResourcePortTOP {

  private boolean isTcp = false;
  private boolean isWS = false;
  private boolean isIpc = false;
  private boolean isFileSystem = false;

  protected ASTResourcePort(/* generated by template ast.ConstructorParametersDeclaration*/
          Optional<ASTStereotype> stereotype,
          de.monticore.types.types._ast.ASTType type,
          String name,
          Optional<montithings._ast.ASTResourceOption> resourceOption,
          String uri,
          boolean incoming,
          boolean outgoing
  ) {
    super(stereotype, type, name, resourceOption, uri, incoming, outgoing);
    if (uri.startsWith("tcp://")){
      isTcp = true;
    }
    else if (uri.startsWith("ipc://")){
      isIpc = true;
    }
    else if (uri.startsWith("ws://")){
      isWS = true;
    }
    else {
      isFileSystem = true;
    }
  }

  protected ASTResourcePort(){
    super();
  }

}
