/* generated from model MontiThings */
/* generated by template ast.AstClass*/

package montithings._ast;


import montiarc._ast.ASTStereotype;

import java.util.Optional;

public class ASTResourcePort extends ASTResourcePortTOP {

  private boolean tcp = false;
  private boolean WS = false;
  private boolean Ipc = false;
  private boolean FileSystem = false;

  protected ASTResourcePort(/* generated by template ast.ConstructorParametersDeclaration*/
          Optional<ASTStereotype> stereotype,
          de.monticore.types.types._ast.ASTType type,
          String name,
          Optional<montithings._ast.ASTResourceOption> resourceOption,
          String uri,
          boolean incoming,
          boolean outgoing
  ) {
    super(stereotype, type, name, resourceOption, uri, incoming, outgoing);
    if (uri.startsWith("tcp://")){
      tcp = true;
    }
    else if (uri.startsWith("ipc://")){
      Ipc = true;
    }
    else if (uri.startsWith("ws://")){
      WS = true;
    }
    else {
      FileSystem = true;
    }
  }
  public boolean isIpc() {
    return Ipc;
  }

  public boolean isWebSocket() {
    return WS;
  }

  public boolean isTcp() {
    return tcp;
  }

  public boolean isFileSystem() {
    return FileSystem;
  }

  protected ASTResourcePort(){
    super();
  }

}
