package bindings._ast;

import arcbasis._ast.ASTComponentInstance;
import arcbasis._ast.ASTComponentType;
import arcbasis._symboltable.ComponentInstanceSymbol;
import arcbasis._symboltable.ComponentInstanceSymbolLoader;
import arcbasis._symboltable.ComponentTypeSymbol;
import arcbasis._symboltable.ComponentTypeSymbolLoader;
import de.se_rwth.commons.logging.Log;

public   class ASTBindingRule extends ASTBindingRuleTOP {

  protected  ComponentTypeSymbolLoader interfaceComponentSymbolLoader;

  protected ComponentInstanceSymbolLoader interfaceInstanceSymbolLoader;

  protected  ComponentTypeSymbolLoader implementationComponentSymbolLoader;

  public ComponentTypeSymbol getInterfaceComponentSymbol ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.GetSymbol*/

    updateInterfaceComponentSymbolLoader();
    if (interfaceComponentSymbolLoader.isSymbolLoaded() && interfaceComponentSymbolLoader.getName() != null && interfaceComponentSymbolLoader.getEnclosingScope() != null) {
      return interfaceComponentSymbolLoader.getLoadedSymbol();
    }
    Log.error("0xA7003x411650880 interfaceComponentSymbol can't return a value. It is empty.");
    // Normally this statement is not reachable
    throw new IllegalStateException();

  }

  /* generated by template core.Method*/
  public  boolean isPresentInterfaceComponentSymbol ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.IsPresentSymbol*/

    updateInterfaceComponentSymbolLoader();
    if (interfaceComponentSymbolLoader.getName() != null && interfaceComponentSymbolLoader.getEnclosingScope() != null) {
      return interfaceComponentSymbolLoader.isSymbolLoaded();
    }
    return false;

  }

  /* generated by template core.Method*/
  protected  void updateInterfaceComponentSymbolLoader ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.UpdateLoader*/

    if (interfaceComponentSymbolLoader == null) {
      interfaceComponentSymbolLoader = new ComponentTypeSymbolLoader(this.getInterfaceComponent().getQName(), this.getEnclosingScope());
    } else {
      if (getInterfaceComponent() != null && !getInterfaceComponent().getQName().equals(interfaceComponentSymbolLoader.getName())) {
        interfaceComponentSymbolLoader.setName(getInterfaceComponent().getQName());
      } else if (getInterfaceComponent() == null && interfaceComponentSymbolLoader.getName() != null) {
        interfaceComponentSymbolLoader.setName(null);
      }
      if (getEnclosingScope() != null && !getEnclosingScope().equals(interfaceComponentSymbolLoader.getEnclosingScope())) {
        interfaceComponentSymbolLoader.setEnclosingScope(getEnclosingScope());
      }else if (getEnclosingScope() == null && interfaceComponentSymbolLoader.getEnclosingScope() != null) {
        interfaceComponentSymbolLoader.setEnclosingScope(null);
      }
    }
  }

  /* generated by template core.Method*/
  public ASTComponentType getInterfaceComponentDefinition ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.GetDefinition*/

    if (isPresentInterfaceComponentDefinition()) {
      return getInterfaceComponentSymbol().getAstNode();
    }
    Log.error("0xA7003x308418005 interfaceComponentDefinition can't return a value. It is empty.");
    // Normally this statement is not reachable
    throw new IllegalStateException();
  }

  /* generated by template core.Method*/
  public  boolean isPresentInterfaceComponentDefinition ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.IsPresentDefinition*/

    return isPresentInterfaceComponentSymbol() && getInterfaceComponentSymbol().isPresentAstNode();

  }

  public ComponentInstanceSymbol getInterfaceInstanceSymbol ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.GetSymbol*/

    updateInterfaceInstanceSymbolLoader();
    if (interfaceInstanceSymbolLoader.isSymbolLoaded() && interfaceInstanceSymbolLoader.getName() != null && interfaceInstanceSymbolLoader.getEnclosingScope() != null) {
      return interfaceInstanceSymbolLoader.getLoadedSymbol();
    }
    Log.error("0xA7003x411650880 interfaceInstanceSymbol can't return a value. It is empty.");
    // Normally this statement is not reachable
    throw new IllegalStateException();

  }

  /* generated by template core.Method*/
  public  boolean isPresentInterfaceInstanceSymbol ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.IsPresentSymbol*/

    updateInterfaceInstanceSymbolLoader();
    if (interfaceInstanceSymbolLoader.getName() != null && interfaceInstanceSymbolLoader.getEnclosingScope() != null) {
      return interfaceInstanceSymbolLoader.isSymbolLoaded();
    }
    return false;

  }

  /* generated by template core.Method*/
  protected  void updateInterfaceInstanceSymbolLoader ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.UpdateLoader*/

    if (interfaceInstanceSymbolLoader == null) {
      interfaceInstanceSymbolLoader = new ComponentInstanceSymbolLoader(this.getInterfaceInstance().getQName(), this.getEnclosingScope());
    } else {
      if (getInterfaceInstance() != null && !getInterfaceInstance().getQName().equals(interfaceInstanceSymbolLoader.getName())) {
        interfaceInstanceSymbolLoader.setName(getInterfaceInstance().getQName());
      } else if (getInterfaceInstance() == null && interfaceInstanceSymbolLoader.getName() != null) {
        interfaceInstanceSymbolLoader.setName(null);
      }
      if (getEnclosingScope() != null && !getEnclosingScope().equals(interfaceInstanceSymbolLoader.getEnclosingScope())) {
        interfaceInstanceSymbolLoader.setEnclosingScope(getEnclosingScope());
      }else if (getEnclosingScope() == null && interfaceInstanceSymbolLoader.getEnclosingScope() != null) {
        interfaceInstanceSymbolLoader.setEnclosingScope(null);
      }
    }
  }

  /* generated by template core.Method*/
  public ASTComponentInstance getInterfaceInstanceDefinition ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.GetDefinition*/

    if (isPresentInterfaceInstanceDefinition()) {
      return getInterfaceInstanceSymbol().getAstNode();
    }
    Log.error("0xA7003x308418005 interfaceInstanceDefinition can't return a value. It is empty.");
    // Normally this statement is not reachable
    throw new IllegalStateException();
  }

  /* generated by template core.Method*/
  public  boolean isPresentInterfaceInstanceDefinition ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.IsPresentDefinition*/

    return isPresentInterfaceInstanceSymbol() && getInterfaceInstanceSymbol().isPresentAstNode();

  }

  public ComponentTypeSymbol getImplementationComponentSymbol ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.GetSymbol*/

    updateImplementationComponentSymbolLoader();
    if (implementationComponentSymbolLoader.isSymbolLoaded() && implementationComponentSymbolLoader.getName() != null && implementationComponentSymbolLoader.getEnclosingScope() != null) {
      return implementationComponentSymbolLoader.getLoadedSymbol();
    }
    Log.error("0xA7003x411650880 implementationComponentSymbol can't return a value. It is empty.");
    // Normally this statement is not reachable
    throw new IllegalStateException();

  }

  /* generated by template core.Method*/
  public  boolean isPresentImplementationComponentSymbol ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.IsPresentSymbol*/

    updateImplementationComponentSymbolLoader();
    if (implementationComponentSymbolLoader.getName() != null && implementationComponentSymbolLoader.getEnclosingScope() != null) {
      return implementationComponentSymbolLoader.isSymbolLoaded();
    }
    return false;

  }

  /* generated by template core.Method*/
  protected  void updateImplementationComponentSymbolLoader ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.UpdateLoader*/

    if (implementationComponentSymbolLoader == null) {
      implementationComponentSymbolLoader = new ComponentTypeSymbolLoader(this.getImplementationComponent().getQName(), this.getEnclosingScope());
    } else {
      if (getImplementationComponent() != null && !getImplementationComponent().getQName().equals(implementationComponentSymbolLoader.getName())) {
        implementationComponentSymbolLoader.setName(getImplementationComponent().getQName());
      } else if (getImplementationComponent() == null && implementationComponentSymbolLoader.getName() != null) {
        implementationComponentSymbolLoader.setName(null);
      }
      if (getEnclosingScope() != null && !getEnclosingScope().equals(implementationComponentSymbolLoader.getEnclosingScope())) {
        implementationComponentSymbolLoader.setEnclosingScope(getEnclosingScope());
      }else if (getEnclosingScope() == null && implementationComponentSymbolLoader.getEnclosingScope() != null) {
        implementationComponentSymbolLoader.setEnclosingScope(null);
      }
    }
  }

  /* generated by template core.Method*/
  public ASTComponentType getImplementationComponentDefinition ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.GetDefinition*/

    if (isPresentImplementationComponentDefinition()) {
      return getImplementationComponentSymbol().getAstNode();
    }
    Log.error("0xA7003x308418005 implementationComponentDefinition can't return a value. It is empty.");
    // Normally this statement is not reachable
    throw new IllegalStateException();
  }

  /* generated by template core.Method*/
  public  boolean isPresentImplementationComponentDefinition ()  {
    /* generated by template _ast.ast_class.refSymbolMethods.IsPresentDefinition*/

    return isPresentImplementationComponentSymbol() && getImplementationComponentSymbol().isPresentAstNode();

  }
}
