# (c) https://github.com/MontiCore/monticore

name: Ubuntu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -U --batch-mode compile package -Dmaven.test.skip=true -Dexec.skip
      - name: Test with Maven
        run: mvn test package -Dexec.skip
